/*
 * RoomManagerInterFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.DMView;

import java.sql.Connection;
import java.sql.ResultSet;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.DMModel.Googs;

import com.DMUtil.DMUtil;
import com.Dao.GoogsDao;
import com.DLuo.*;

/**
 *
 * @author  __USER__
 */
public class Gaihuo extends javax.swing.JInternalFrame {
	//标记 修改之前是否执行选择列表的操作
	public static int f=0;
	//end
	public static DMUtil dmutil = new DMUtil();
	public static GoogsDao googsdao = new GoogsDao();
	/** Creates new form RoomManagerInterFrm */
	public Gaihuo() {
		
		initComponents();
        Dgaihuo.fillTable(new Googs());
		this.setLocation(200, 50);
	}



	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		jLabel1 = new javax.swing.JLabel();
		huohao = new javax.swing.JTextField();
		huoming1 = new javax.swing.JTextField();
		canghao1 = new javax.swing.JTextField();
		jb_search = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		table = new javax.swing.JTable();
		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		huohao1 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		huoming = new javax.swing.JTextField();
		jb_modify = new javax.swing.JButton();
		jb_chu =new javax.swing.JButton();
		jb_ru =new javax.swing.JButton();
		jb_exit = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		canghao = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		huojia = new javax.swing.JTextField();
		shuliang = new javax.swing.JTextField();
		danjia = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();

		setClosable(true);
		setIconifiable(true);
		setTitle("货物信息修改");

		jLabel1.setText("货物编号");
		jLabel8.setText("货物名称");
		jLabel9.setText("仓库编号");

		jb_search.setIcon(new javax.swing.ImageIcon(
				"D:\\Myelipse\\images4\\search.png")); // NOI18N
		jb_search.setText("查询");
		jb_search.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Dgaihuo.jb_searchActionPerformed(evt);
			}
		});

		table.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "货物编号", "货物名", "仓库编号", "所在货架","数量","单价" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		table.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				Dgaihuo.tableMousePressed(evt);
				f=1;
			}
		});
		jScrollPane1.setViewportView(table);

		jPanel1.setBorder(javax.swing.BorderFactory
				.createTitledBorder("操作"));

		jLabel2.setText("货物编号");


		jLabel3.setText("货物名");
		
        jLabel4.setText("货仓编号");
		
		jLabel5.setText("货架编号");
		
		jLabel6.setText("数量");
		
		jLabel7.setText("单价");

		jb_modify.setIcon(new javax.swing.ImageIcon(
				"D:\\Myelipse\\images4\\modify.png")); // NOI18N
		jb_modify.setText("修改");
		jb_modify.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Dgaihuo.jb_modifyActionPerformed(evt);
			}
		});
		
		
		jb_chu.setIcon(new javax.swing.ImageIcon(
				"D:\\Myelipse\\images4\\modify.png")); // NOI18N
		jb_chu.setText("出库");
		jb_chu.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				DGuanliyuan.jMenuItem2ActionPerformed(evt);
			}
		});
		

		jb_ru.setIcon(new javax.swing.ImageIcon(
				"D:\\Myelipse\\images4\\modify.png")); // NOI18N
		jb_ru.setText("入库");
		jb_ru.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				DGuanliyuan.jMenuItem3ActionPerformed(evt);
			}
		});
		
		
		jb_exit.setIcon(new javax.swing.ImageIcon(
				"D:\\Myelipse\\images4\\exit.png")); // NOI18N
		jb_exit.setText("退出");
		jb_exit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jb_exitActionPerformed(evt);
			}
		});

		
		

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(39, 39, 39)
										.addComponent(jb_modify)
										.addComponent(jb_chu)
										.addComponent(jb_ru)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												162, Short.MAX_VALUE)
										
										.addComponent(jb_exit)
										.addGap(64, 64, 64))
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(21, 21, 21)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel4)
														.addComponent(jLabel2))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
													
														.addComponent(
																canghao)
														

														.addComponent(
																huohao1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																92,
																Short.MAX_VALUE))
										.addGap(62, 62, 62)
										.addComponent(jLabel3)
										.addGap(10, 10, 10)
										.addComponent(
												huoming,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												116, Short.MAX_VALUE)
										.addGap(62, 62, 62)
										.addComponent(jLabel5)
										.addGap(10, 10, 10)
										.addComponent(
												huojia,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												116, Short.MAX_VALUE)
										.addGap(62, 62, 62)
										.addComponent(jLabel6)
										.addGap(10, 10, 10)
										.addComponent(
												shuliang,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												116, Short.MAX_VALUE)
										.addGap(62, 62, 62)
										.addComponent(jLabel7)
										.addGap(10, 10, 10)
										.addComponent(
												danjia,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												116, Short.MAX_VALUE)
										));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addGap(19, 19, 19)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																huohao1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel3)
														.addComponent(
																huoming,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel5)
														.addComponent(
																huojia,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel6)
														.addComponent(
																shuliang,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel7)
														.addComponent(
																danjia,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(33, 33, 33)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(
																canghao,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												60, Short.MAX_VALUE)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jb_modify)
														.addComponent(jb_chu)
														.addComponent(jb_ru)
														.addComponent(jb_exit))
										.addContainerGap()));

		
		
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(41, 41, 41)
								.addComponent(jLabel1)
								.addGap(50, 50, 50)
								.addComponent(huohao, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								
				
						
								.addGap(41, 41, 41)
								.addComponent(jLabel8)
								.addGap(50, 50, 50)
								.addComponent(huoming1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
							
				
						
								.addGap(41, 41, 41)
								.addComponent(jLabel9)
								.addGap(50, 50, 50)
								.addComponent(canghao1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jb_search).addGap(80, 80, 80))
				
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING,
												false)
												.addComponent(
														jPanel1,
														javax.swing.GroupLayout.Alignment.LEADING,
														0,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														379, Short.MAX_VALUE))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(huohao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								
								
												.addComponent(jLabel8)
												.addComponent(huoming1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								
												.addComponent(jLabel9)
												.addComponent(jb_search)
												.addComponent(canghao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								
				.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										111,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(jPanel1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE).addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents



	private void jb_exitActionPerformed(java.awt.event.ActionEvent evt) {
		int result = JOptionPane.showConfirmDialog(null, "退出修改？");
		if (result == 0) {

			this.dispose();
		}
	}


	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	public static javax.swing.JTextField huohao1;
	public static javax.swing.JLabel jLabel1;
	public static javax.swing.JLabel jLabel2;
	public static javax.swing.JLabel jLabel3;
	public static javax.swing.JLabel jLabel4;
	public static javax.swing.JLabel jLabel5;
	public static javax.swing.JLabel jLabel6;
	public static javax.swing.JLabel jLabel7;
	public static javax.swing.JLabel jLabel8;
	public static javax.swing.JLabel jLabel9;
	public static javax.swing.JPanel jPanel1;
	public static javax.swing.JScrollPane jScrollPane1;
	public static javax.swing.JButton jb_exit;
	public static javax.swing.JButton jb_modify;
	public static javax.swing.JButton jb_chu;
	public static javax.swing.JButton jb_ru;
	public static javax.swing.JButton jb_search;
	public static javax.swing.JTextField huohao;
	public static javax.swing.JTextField huoming1;
	public static javax.swing.JTextField canghao1;
	public static javax.swing.JTextField canghao;
	public static javax.swing.JTextField huoming;
	public static javax.swing.JTextField huojia;
	public static javax.swing.JTextField shuliang;
	public static javax.swing.JTextField danjia;
	public static javax.swing.JTable table;
	// End of variables declaration//GEN-END:variables


}
