/*
 * MainFrm.java 
 *管理员
 * Created on __DATE__, __TIME__
 */

package com.DMView;

import javax.swing.JOptionPane;

import com.*;
import com.DLuo.DGuanliyuan;

/**
 *
 * @author  __USER__
 */
public class Guanliyuan extends javax.swing.JFrame {

	/** Creates new form MainFrm */
	public Guanliyuan() {
		initComponents();
		this.setExtendedState(MAXIMIZED_BOTH);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {


		table = new javax.swing.JDesktopPane();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenuItem3 = new javax.swing.JMenuItem();
		jMenu9 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenuItem5 = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();
		enter = new javax.swing.JMenuItem();
		jMenu7 = new javax.swing.JMenu();
		jMenuItem6 = new javax.swing.JMenuItem();
		jMenuItem7 = new javax.swing.JMenuItem();
		jMenuItem8 = new javax.swing.JMenuItem();
		jMenuItem9 = new javax.swing.JMenuItem();



		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("管理员界面");

		jMenu1.setIcon(new javax.swing.ImageIcon(
				"D:\\Myelipse\\images4\\bookTypeManager.png")); // NOI18N
		jMenu1.setText("货物出入库");

		jMenuItem2.setIcon(new javax.swing.ImageIcon(
				"D:\\Myelipse\\images4\\modify.png")); // NOI18N
		jMenuItem2.setText("货物出库");
		jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				DGuanliyuan.jMenuItem2ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem2);

		jMenuItem3.setIcon(new javax.swing.ImageIcon(
				"D:\\Myelipse\\images4\\delete.png")); // NOI18N
		jMenuItem3.setText("货物入库");
		jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				DGuanliyuan.jMenuItem3ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem3);

		jMenuBar1.add(jMenu1);

		jMenu9.setIcon(new javax.swing.ImageIcon(
				"D:\\Myelipse\\images4\\bookManager.png")); // NOI18N
		jMenu9.setText("货仓信息管理");

		

		jMenuItem1.setIcon(new javax.swing.ImageIcon(
				"D:\\Myelipse\\images4\\modify.png")); // NOI18N
		jMenuItem1.setText("创建货仓");
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				DGuanliyuan.jMenuItem1ActionPerformed(evt);
			}
		});
		jMenu9.add(jMenuItem1);

		jMenuItem5.setIcon(new javax.swing.ImageIcon(
				"D:\\Myelipse\\images4\\delete.png")); // NOI18N
		jMenuItem5.setText("删除货仓");
		jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				DGuanliyuan.jMenuItem5ActionPerformed(evt);
			}
		});
		jMenu9.add(jMenuItem5);

		jMenuBar1.add(jMenu9);

		jMenu2.setIcon(new javax.swing.ImageIcon(
				"C:\\Documents and Settings\\Administrator\\桌面\\寝室管理.jpg")); // NOI18N
		jMenu2.setText("货物信息管理");


		enter.setIcon(new javax.swing.ImageIcon(
				"D:\\Myelipse\\images3\\add.png")); // NOI18N
		enter.setText(" 货物信息查询与修改");
		enter.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				DGuanliyuan.enterActionPerformed(evt);
			}
		});
		jMenu2.add(enter);
		


		jMenuBar1.add(jMenu2);

		jMenu7.setIcon(new javax.swing.ImageIcon(
				"D:\\Myelipse\\images4\\search.png")); // NOI18N
		jMenu7.setText("账号管理");

		jMenuItem6.setIcon(new javax.swing.ImageIcon(
				"D:\\Myelipse\\images4\\search.png")); // NOI18N
		jMenuItem6.setText("信息管理");
		jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				DGuanliyuan.jMenuItem6ActionPerformed(evt);
			}
		});
		jMenu7.add(jMenuItem6);

		jMenuItem7.setIcon(new javax.swing.ImageIcon(
				"D:\\Myelipse\\images4\\search.png")); // NOI18N
		jMenuItem7.setText("密码修改");
		jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				DGuanliyuan.jMenuItem7ActionPerformed(evt);
			}
		});
		jMenu7.add(jMenuItem7);
		
		
		jMenuItem8.setIcon(new javax.swing.ImageIcon(
				"D:\\Myelipse\\images4\\search.png")); // NOI18N
		jMenuItem8.setText("新增用户账号");
		jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				DGuanliyuan.jMenuItem8ActionPerformed(evt);
			}
		});
		jMenu7.add(jMenuItem8);
		
		jMenuItem9.setIcon(new javax.swing.ImageIcon(
				"D:\\Myelipse\\images4\\search.png")); // NOI18N
		jMenuItem9.setText("删除用户账号");
		jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				DGuanliyuan.jMenuItem9ActionPerformed(evt);
			}
		});
		jMenu7.add(jMenuItem9);

		
		jMenuBar1.add(jMenu7);


		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(table,
				javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(table,
				javax.swing.GroupLayout.Alignment.TRAILING,
				javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents



	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Guanliyuan().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	public static javax.swing.JMenuItem enter;
	public static javax.swing.JMenu jMenu1;
	public static javax.swing.JMenu jMenu2;
	public static javax.swing.JMenu jMenu7;
	public static javax.swing.JMenu jMenu9;
	public static javax.swing.JMenuBar jMenuBar1;
	public static javax.swing.JMenuItem jMenuItem1;
	public static javax.swing.JMenuItem jMenuItem2;
	public static javax.swing.JMenuItem jMenuItem3;
	public static javax.swing.JMenuItem jMenuItem5;
	public static javax.swing.JMenuItem jMenuItem6;
	public static javax.swing.JMenuItem jMenuItem7;
	public static javax.swing.JMenuItem jMenuItem8;
	public static javax.swing.JMenuItem jMenuItem9;
	public static javax.swing.JDesktopPane table;
	// End of variables declaration//GEN-END:variables

}