/*
 * LoginFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.DMView;

import java.awt.Font;
import java.sql.Connection;

import javax.swing.JOptionPane;
import javax.swing.UIManager;

import com.DMModel.User;
import com.DMUtil.DMUtil;
import com.DMUtil.StringUtil;
import com.Dao.UserDao;
import com.DLuo.*;
/**
 *
 * @author  __USER__
 */
public class LoginFrm extends javax.swing.JFrame {
	private DMUtil dmutil = new DMUtil();
	private UserDao userdao = new UserDao();

	/** Creates new form LoginFrm */
	public LoginFrm() {

		Font font = new Font("Dialog", Font.PLAIN, 12);
		java.util.Enumeration keys = UIManager.getDefaults().keys();
		while (keys.hasMoreElements()) {
			Object key = keys.nextElement();
			Object value = UIManager.get(key);
			if (value instanceof javax.swing.plaf.FontUIResource) {
				UIManager.put(key, font);
			}
		}
		initComponents();
		this.setLocationRelativeTo(null);
		this.filltable();
	}

	public void filltable() {
		User user1 = new User();
		User user2 = new User();
		user1.setUserName("员工");
		user2.setUserName("管理员");
		user1.setId(1 + "");
		user2.setId(2 + "");
		jcb_choose.addItem(user1);
		jcb_choose.addItem(user2);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	public void initComponents() {

jLabel1 = new javax.swing.JLabel();
jLabel2 = new javax.swing.JLabel();
jLabel3 = new javax.swing.JLabel();
userNameTxt = new javax.swing.JTextField();
userPasswordTxt = new javax.swing.JPasswordField();
jb_login = new javax.swing.JButton();
jb_reset = new javax.swing.JButton();
jcb_choose = new javax.swing.JComboBox();
jLabel4 = new javax.swing.JLabel();

setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
setTitle("欢迎登陆仓库管理系统");
setResizable(false);

jLabel1.setFont(new java.awt.Font("楷体", 0, 24));

jLabel1.setText("         仓库管理系统");

//jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Myelipse\\images1\\userName.png")); // NOI18N
jLabel2.setText("用户名：");

//jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Myelipse\\images1\\password.png")); // NOI18N
jLabel3.setText("密码：");

userNameTxt.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
	userNameTxtActionPerformed(evt);
}
});

//jb_login.setIcon(new javax.swing.ImageIcon("D:\\Myelipse\\images4\\login.png")); // NOI18N
jb_login.setText("登录");
jb_login.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
	jb_loginActionPerformed(evt);
}
});

//jb_reset.setIcon(new javax.swing.ImageIcon("D:\\Myelipse\\images4\\reset.png")); // NOI18N
jb_reset.setText("重置");
jb_reset.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
	jb_resetActionPerformed(evt);
}
});


//jLabel4.setIcon(new javax.swing.ImageIcon("C:\\\\Documents and Settings\\\\Administrator\\\\桌面\\\\用户类型.jpg")); // NOI18N 
jLabel4.setText("用户类型：");


javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(21, 21, 21)
.addComponent(jLabel1)
.addContainerGap(58, Short.MAX_VALUE))
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
.addGroup(layout.createSequentialGroup()
.addContainerGap()
.addComponent(jLabel4)
.addGap(42, 42, 42)
.addComponent(jcb_choose, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(103, 103, 103)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
.addComponent(jLabel3)
.addComponent(jLabel2)))
.addGroup(layout.createSequentialGroup()
.addGap(104, 104, 104)
.addComponent(jb_login)))
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(42, 42, 42)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(userNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
.addComponent(userPasswordTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jb_reset)
.addGap(25, 25, 25)))))
.addGap(79, 79, 79))
);
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(27, 27, 27)
.addComponent(jLabel1)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel2)
.addComponent(userNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(26, 26, 26)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel3)
.addComponent(userPasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(26, 26, 26)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jLabel4)
.addComponent(jcb_choose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(34, 34, 34)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jb_login)
.addComponent(jb_reset))
.addContainerGap(43, Short.MAX_VALUE))
);

pack();
}// </editor-fold>

	//GEN-END:initComponents
	private  void jb_loginActionPerformed(java.awt.event.ActionEvent evt) {
		String userName = LoginFrm.userNameTxt.getText();
		String userPassword = new String(LoginFrm.userPasswordTxt.getPassword());
		if (StringUtil.isEmpty(userName)) {
			JOptionPane.showMessageDialog(null, "用户名不能为空！");
			return;
		} else if (StringUtil.isEmpty(userPassword)) {
			JOptionPane.showMessageDialog(null, "密码不能为空!");
			return;
		}
		User user1 = (User) LoginFrm.jcb_choose.getSelectedItem();
		String userright = user1.getUserName();
		User user = new User(userName, userPassword,userright);
		Connection con = null;
		try {
			con = dmutil.getCon();
			User currentuser = userdao.Login(con, user);
			if (currentuser != null) {
				if (userright.equals("管理员")) {
					this.dispose();
					Guanliyuan main = new Guanliyuan();
					main.setVisible(true);
				} else if (userright.equals("员工")) {
					this.dispose();
					Yuangong main2 = new Yuangong();
					main2.setVisible(true);
				}
			}
			 else {
					JOptionPane.showMessageDialog(null, "用户名密码错误!");
				}
			
			//整个程序缓存某些数据 
			com.DMView.Xinxi.name2=currentuser.getname();
			com.DMView.Xinxi.phone2=currentuser.getPhone();
			com.DMView.Xinxi.position2=currentuser.getposition();
			com.DMView.Xinxi.remark2=currentuser.getRemark();
		//end
			
		} catch (Exception e) {
			JOptionPane.showInternalMessageDialog(null, "登陆失败");
			e.printStackTrace();
		}
	}

	public static void jb_resetActionPerformed(java.awt.event.ActionEvent evt) {
		LoginFrm.userNameTxt.setText("");
		LoginFrm.userPasswordTxt.setText("");
	}

	public static void userNameTxtActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling cod
	}
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new LoginFrm().setVisible(true);
			}
		});
	}
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	public static javax.swing.JLabel jLabel1;
	public static javax.swing.JLabel jLabel2;
	public static javax.swing.JLabel jLabel3;
	public static javax.swing.JLabel jLabel4;
	public static javax.swing.JButton jb_login;
	public static javax.swing.JButton jb_reset;
	public static javax.swing.JComboBox jcb_choose;
	public static javax.swing.JTextField userNameTxt;
	public static javax.swing.JPasswordField userPasswordTxt;
	// End of variables declaration//GEN-END:variables

}