/*
 * StudentInterFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.DMView;


import javax.swing.JOptionPane;
import com.DLuo.*;
import com.DMUtil.DMUtil;
import com.Dao.*;
/**
 *
 * @author  __USER__
 */
public class Xinxi extends javax.swing.JInternalFrame {
	
	//缓存的数据
	public static String name2;
	public static String phone2;
	public static String position2;
	public static String remark2;
	public static String id2;
	//end
	
	
	
	public static DMUtil dmutil = new DMUtil();
	public static XinxiDao xinxidao = new XinxiDao();
	
	/** Creates new form StudentInterFrm */
	public Xinxi() {
		initComponents();
		this.setLocation(200, 50);
	}



	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

new javax.swing.ButtonGroup();
jLabel1 = new javax.swing.JLabel();
nameTxt = new javax.swing.JTextField(name2);  //输入姓名
jLabel3 = new javax.swing.JLabel();
jLabel4 = new javax.swing.JLabel();
jLabel6 = new javax.swing.JLabel();
jb_regist = new javax.swing.JButton();
jb_exit = new javax.swing.JButton();
phoneTxt = new javax.swing.JTextField(phone2);   //输入电话号
positionTxt = new javax.swing.JTextField(position2);   //输入职位
remarkTxt = new javax.swing.JTextField(remark2);  //输入备注


setClosable(true);
setIconifiable(true);
setResizable(true);
setTitle("信息管理");

jLabel1.setText("姓名：");


jLabel3.setText("电话号：");

jLabel4.setText("职位：");


jLabel6.setText("备注：");


jb_regist.setIcon(new javax.swing.ImageIcon("D:\\Myelipse\\images4\\add.png")); // NOI18N
jb_regist.setText("修改");
jb_regist.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
try {
	DXinxi.jb_registActionPerformed(evt);
} catch (Exception e) {
	// TODO Auto-generated catch block
	e.printStackTrace();
}
}
});

jb_exit.setIcon(new javax.swing.ImageIcon("D:\\Myelipse\\images4\\exit.png")); // NOI18N
jb_exit.setText("退出");
jb_exit.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jb_exitActionPerformed(evt);
}
});


javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addContainerGap()
.addComponent(jLabel6)
.addGap(192, 192, 192))
.addGroup(layout.createSequentialGroup()
.addContainerGap()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addComponent(jLabel1)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGroup(layout.createSequentialGroup())

.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
.addGroup(layout.createSequentialGroup()
.addComponent(jLabel4)
.addGap(20, 20, 20))
.addGroup(layout.createSequentialGroup()
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
.addComponent(jLabel3))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
.addComponent(remarkTxt)
.addComponent(positionTxt)
.addComponent(phoneTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
.addGroup(layout.createSequentialGroup()
.addContainerGap()
.addComponent(jb_regist))
.addGroup(layout.createSequentialGroup()
.addGap(125, 125, 125)
.addComponent(jb_exit)))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
);

layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
.addGroup(layout.createSequentialGroup()
.addContainerGap())
.addGroup(layout.createSequentialGroup()
.addGap(26, 26, 26)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel1)
.addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(29, 29, 29)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel3)
.addComponent(phoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(26, 26, 26)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel4)
.addComponent(positionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(30, 30, 30)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel6)
.addComponent(remarkTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(29, 29, 29)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jb_regist)
.addComponent(jb_exit))))
.addContainerGap(18, Short.MAX_VALUE))
);

pack();
}// </editor-fold>

	//GEN-END:initComponents

	private void jb_exitActionPerformed(java.awt.event.ActionEvent evt) {
		int a = JOptionPane.showConfirmDialog(null, "确认要退出？");
		if (a == 0) {
			this.dispose();
		}
}

	

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	public static  javax.swing.JTextField remarkTxt;
	public static  javax.swing.JTextField positionTxt;
	public static  javax.swing.JLabel jLabel1;
	public static  javax.swing.JLabel jLabel3;
	public static  javax.swing.JLabel jLabel4;
	public static  javax.swing.JLabel jLabel6;
	public static  javax.swing.JButton jb_exit;
	public static  javax.swing.JButton jb_regist;
	public static  javax.swing.JTextField nameTxt;
	public static  javax.swing.JTextField phoneTxt;


	// End of variables declaration//GEN-END:variables

}